name: Issue Background Agent

on:
  issues:
    types: [opened]

jobs:
  trigger-background-agent:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      
    - name: Clone cursor-background-agent-api
      run: |
        git clone https://github.com/mjdierkes/cursor-background-agent-api.git background-agent
        cd background-agent
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'background-agent/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd background-agent
        npm ci
      
    - name: Build project
      run: |
        cd background-agent
        npm run build
      
    - name: Create background composer task
      run: |
        cd background-agent
        node dist/cli.js create \
          --task-description "$TASK_DESCRIPTION" \
          --repository-url "${{ github.event.repository.clone_url }}" \
          --format json
      env:
        CURSOR_SESSION_TOKEN: ${{ secrets.CURSOR_SESSION_TOKEN }}
        TASK_DESCRIPTION: >
          ${{ github.event.issue.body }}
        
    - name: Comment on issue
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🤖 **Background Agent Triggered**
            
            A background agent has been started to analyze this issue and provide implementation suggestions.
            
            The agent will review:
            - Issue description and requirements
            - Repository codebase
            - Potential implementation approaches
            
            Results will be available in the Cursor Background Composer interface.`
          })