name: Issue Background Agent

on:
  issues:
    types: [opened]

jobs:
  trigger-background-agent:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Create background composer task
      run: |
        npm run start create \
          --task-description "$TASK_DESCRIPTION" \
          --repository-url "${{ github.event.repository.clone_url }}" \
          --format json
      env:
        CURSOR_SESSION_TOKEN: ${{ secrets.CURSOR_SESSION_TOKEN }}
        TASK_DESCRIPTION: |
          Handle GitHub issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}

          Issue Details:
          - Title: ${{ github.event.issue.title }}
          - Author: ${{ github.event.issue.user.login }}
          - Labels: ${{ join(github.event.issue.labels.*.name, ', ') }}
          - Body: ${{ github.event.issue.body }}
          - URL: ${{ github.event.issue.html_url }}
          
          Please analyze this issue and provide suggestions for implementation or resolution.
        
    - name: Comment on issue
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🤖 **Background Agent Triggered**
            
            A background agent has been started to analyze this issue and provide implementation suggestions.
            
            The agent will review:
            - Issue description and requirements
            - Repository codebase
            - Potential implementation approaches
            
            Results will be available in the Cursor Background Composer interface.`
          })